### PR TITLE
Add a patch file for nginx-1.12.0

### PR DESCRIPTION
**Pull request by tsuyoshizawa**

### CODE REVIEW

**Comment by dataich** [comment]
Patch file for previous Nginx version seems to have patches for following files.

- ngx_http_header_filter_module.c
- ngx_http_request.h
- ngx_http_special_response.c

Your patch file has no diff with the files above. Is it ok?

e.g) [nginx-1.11.x-too-many-requests-retryafter.patch](https://github.com/nulab/nginx-too-many-requests-retryafter-patch/blob/8cae3a743188b32987985fb39bef2905789c774d/nginx-1.11.x-too-many-requests-retryafter.patch)

**Comment by tsuyoshizawa** [comment]
Could you check Nginx latest code?
These files include we patched code excluding `ngx_http_limit_req_module.c`.

e.g. https://github.com/nginx/nginx/blob/release-1.12.0/src/http/ngx_http_special_response.c#L365-L371

**Comment by dataich** [comment]
I see. I checked the following latest code and confirmed we don't need to patch to it. 

- ngx_http_header_filter_module.c
- ngx_http_request.h
- ngx_http_special_response.c

Thanks!

**Comment by dataich** [comment]
I confirmed that `Retry-After` header was added correctly. Thanks! @tsuyoshizawa

**Pull request merged**
